spring.application.name=HSF302_ClassProject_1

spring.datasource.url=jdbc:mysql://localhost:3306/hsf302_classproject_1?useSSL=false
spring.datasource.username=postgres
spring.datasource.password=Dongl@m2026
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

